### PR TITLE
Use RobotJS from npm.

### PR DESCRIPTION
**Pull request by octalmage**
Now that we have modifiers implemented, ScreenCat can use the official RobotJS build. This build includes Linux support and Windows support will be done in a few weeks. 
#3.

### CODE REVIEW

**Comment by octalmage** [comment]
Just want to add that the Windows build has been out for a few weeks and it's working great!

**Comment by brandly** [comment]
Looks like RobotJs v0.2.4 is out now. (I'm sure you know this :smile:)

I'm having trouble running `screencat` from source though. It looked like RobotJS was throwing, so I pointed it at `^0.2.4`. It still threw on install. [Here's the output](https://gist.github.com/brandly/3a7cc3de0d37f1367cab).

If I directly clone RobotJS and `npm install`, it seems to install smoothly tho. Any idea what I'm doing wrong?

**Comment by maxogden** [comment]
hmm maybe the code published to robotjs on npm is different from the code in the git repo...

**Comment by octalmage** [comment]
Node.js v4 isn't supported by the RobotJS version published to npm, but the version on GitHub has been updated. I'll be publishing a new version soon.

**Comment by octalmage** [comment]
A ton of things changed internally with Node.js v4 and nan v2, so it required a rewrite.

**Comment by octalmage** [comment]
@brandly try now! RobotJS v0.3.0 was released with Node.js v4 support.

**Comment by brandly** [comment]
looks great!! thanks, @octalmage

**Comment by octalmage** [comment]
@brandly no problem! Thanks for testing!

**Comment by octalmage** [comment]
@maxogden this is good to merge! This will add both Windows and Node.js v4 support.

**Comment by maxogden** [comment]
OK awesome

**Comment by maxogden** [comment]
Nice, works a charm!

**Comment by maxogden** [comment]
published a new release https://github.com/maxogden/screencat/releases/tag/v3.0.0 if anyone can build + test windows and mac binaries let me know and I can upload them!

**Comment by octalmage** [comment]
Awesome! I'll work on a Windows build later today.

**Comment by chenkaigithub** [comment]
@maxogden I want to test windows! Thank you!

**Comment by maxogden** [comment]
@chenkaigithub hi, thanks :) I just realized I don't have a way to build a release for windows, because I don't have a windows computer at the moment.

Could you try building it? You will [need Visual studio C++](https://github.com/nodejs/node-gyp) installed so you can build the native modules. Here are instructions for cmd.exe:

```
git clone https://github.com/maxogden/screencat.git
cd screencat
npm install
npm install electron-rebuild
.\node_modules\.bin\electron-rebuild.cmd
npm start
```

If any of those fail, can you share the error messages?

**Comment by chenkaigithub** [comment]
Hi Maxogen,
I built and test Windows version,it's workable! Great!

**Comment by maxogden** [comment]
@chenkaigithub wow cool, can you run two at once and screenshare with yourself? if you get it working can you send a screenshot?

**Comment by chenkaigithub** [comment]
Sure！ I willl send screenshots later!

**Comment by octalmage** [comment]
Sorry forgot about this, let me know if you need anything!

**Comment by chenkaigithub** [comment]
screenshot1
screen shot 2015-12-31 at 10 11 18 am

**Comment by maxogden** [comment]
@chenkaigithub WOW!!! So awesome! Thanks for testing, that is really cool

**Comment by octalmage** [comment]
Woohoo! This is awesome!

**Pull request merged**
