### PR TITLE
some small ui improvements, mostly button styling

### PR DESCRIPTION
**Pull request by jsimplicio**
screen shot 2015-11-03 at 2 21 40 pm

### CODE REVIEW

**Comment by maxogden** [comment]
oooh looks super nice, thanks!

**Comment by maxogden** [comment]
I added a little npm script for compiling the css here: https://github.com/maxogden/screencat/commit/40fc05bb669b0721c68ba2f4078ea51a6ff1fa5b

4.1.0 is released now with your changes as well: https://github.com/maxogden/screencat/releases/tag/v4.1.0

Finally, since this was an awesome contribution I added you to the collaborators on this project: https://github.com/maxogden/screencat/blob/master/collaborators.md. I use the [Open Open Source](http://openopensource.org/) method to run this project, meaning you can now close issues, merge pull requests, etc (if you want to). If you have other ideas for how to improve ScreenCat, just open an issue.

Thanks!

**Comment by jsimplicio** [comment]
@maxogden I demand more cats. But seriously, thank you! This is great. :)

**Comment by maxogden** [comment]
Oh yea the lack of cats in the UI is definitely an issue. Easter egg suggestions welcome.

Also I just updated all the screenshots and the remote page to use the new styles http://maxogden.github.io/screencat/remote

**Pull request merged**
