### PR TITLE
Continuing UI styling

### PR DESCRIPTION
**Pull request by jsimplicio**
Few more small styling changes and fixes for now.

### CODE REVIEW

**Comment by maxogden** [comment]
nice, I like the grey background

screen shot 2015-11-04 at 1 34 27 pm

**Comment by jsimplicio** [comment]
@maxogden Thanks! I made an icon for 'back' arrow and for 'quit' put together with https://icomoon.io/.
I'm not sure if I should be adding any prefixes to CSS properties like `-webkit-` because I don't know how this works. I used a light gradient on the header and want to make sure it's working.

**Comment by maxogden** [comment]
the only browser we really need to support with eveyrthing is Chrome, since thats what Electron uses. the 'remote viewer' page currently works in Chrome and Firefox but its just a form with a button, so doesnt have a back button I don't think http://maxogden.github.io/screencat/remote

**Comment by jsimplicio** [comment]
latest. I think I'm done for now.
screen shot 2015-11-04 at 7 20 28 pm

**Comment by jsimplicio** [comment]
@maxogden Do you know why this is failing? It looks like it's something on the js files, but I'm not sure if I did something wrong.

**Comment by maxogden** [comment]
oh dang thats my fault: https://travis-ci.org/maxogden/screencat/builds/89354735#L326

I use the http://standardjs.com/ JS style checker but accidentally pushed improperly styled code

**Comment by maxogden** [comment]
published as 4.2.0 https://github.com/maxogden/screencat/releases/tag/v4.2.0

**Pull request merged**
