### PR TITLE
UI improvements

### PR DESCRIPTION
**Pull request by jsimplicio**
Scrapped the words on header actions and turned them into little buttons

screencat-1
screencat-2
screencat-3
screencat-4

### CODE REVIEW

**Comment by maxogden** [comment]
:+1:

**Comment by maxogden** [comment]
@jsimplicio I think there were some unintended weird UI things introduced:

screen shot 2015-11-06 at 11 24 02 am

To test that case, here's what I do:

1. open 2 terminal tabs
2. `cd` into `screencat` on both of them
3. run `npm start` on both of them
4. you should have 2 cats in the menubar
5. share on one, join on the other

**Comment by maxogden** [comment]
Also I like the new quit and back icons, but the only thing I'm unsure of is if the X is the right thing to use for a "quit" action. I think usually X is used for closing a window, so it might be a little confusing in terms of expected outcome to the user. Might not be a big deal though, just thought I'd mention it

**Comment by jsimplicio** [comment]
Hey @maxogden sorry for the delay. I'll fix the unintended case ASAP.

I think the 'quit' and the X button confusion is valid. While minimizing the buttons UI by just placing icons to replace words, I got carried away. I do believe quit will fit more nicely in this case! Thanks for pointing it out.

**Comment by maxogden** [comment]
no worries, and no rush! most of the projects I work on have 0 deadlines or
schedules

On Monday, November 16, 2015, Julia <notifications@github.com> wrote:

> Hey @maxogden <https://github.com/maxogden> sorry for the delay. I'll fix
> the unintended case ASAP.
>
> I think the 'quit' and the X button confusion is valid. While minimizing
> the buttons UI by just placing icons to replace words, I got carried away.
> I do believe quit will fit more nicely in this case! Thanks for pointing it
> out.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/maxogden/screencat/pull/44#issuecomment-157130924>.
>


-- 
Sent from my phone

**Pull request merged**
